language: php
php:
  - 5.4
  - 5.6
  - 5.7

script:
  # Check php script syntax
  - bash .travis.phplint.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net##reception"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    recipients:
      - utilizator.receptie123@gmail.com  
    on_success: change
    on_failure: always
